# Generated by Django 6.0.6 on 2026-06-25 11:35

import apps.members.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 11 digits, numbers only (no spaces or symbols).', regex='^\\d{11}$')])),
                ('nin_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nin', message='NIN must be exactly 11 digits, numbers only (no spaces or symbols).', regex='^\\d{11}$')])),
                ('date_of_birth', models.DateField()),
                ('institution', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate_alumni', 'Graduate/Alumni')], max_length=20)),
                ('passport_photo', models.ImageField(upload_to='members/passports/%Y/%m/', validators=[apps.members.validators.MaxFileSizeValidator(max_mb=5)])),
                ('membership_id', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('voting_status', models.BooleanField(default=False, help_text='Auto-managed: set True when approval_status becomes Approved.', verbose_name='Eligible to vote')),
                ('alumni_status', models.BooleanField(default=False, verbose_name='Is alumni')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.association')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-registration_date'],
                'permissions': [('approve_member', "Can approve or reject a member's registration"), ('manage_alumni_status', 'Can convert a member to alumni status')],
            },
        ),
        migrations.CreateModel(
            name='AlumniRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=255)),
                ('current_role', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_conversions', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_record', to='members.member')),
            ],
            options={
                'verbose_name': 'Alumni Record',
                'verbose_name_plural': 'Alumni Records',
            },
        ),
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='members/receipts/%Y/%m/', validators=[apps.members.validators.MaxFileSizeValidator(max_mb=5)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(help_text='Plain FK (not one-to-one) so a rejected member can reapply without losing history.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Application',
                'verbose_name_plural': 'Registration Applications',
                'ordering': ['-submitted_at'],
                'permissions': [('review_application', 'Can approve or reject a registration application')],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['association', 'approval_status'], name='members_mem_associa_67345b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['association', 'alumni_status'], name='members_mem_associa_78d761_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['association', 'category'], name='members_mem_associa_dfc9bd_idx'),
        ),
    ]
