# Generated by Django 6.0.6 on 2026-06-26 18:04

import apps.members.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nin_number',
            field=models.CharField(max_length=11, unique=True, validators=[apps.members.validators.nin_validator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[apps.members.validators.phone_number_validator]),
        ),
    ]
