# Generated by Django 6.0.6 on 2026-06-25 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(help_text="Short code used in membership IDs etc., e.g. 'MSA'.", max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='associations/logos/')),
                ('description', models.TextField(blank=True)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive associations are hidden from new registrations but their historical data is kept.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('about_text', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='associations/hero/')),
                ('facebook_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X (Twitter) URL')),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='core.association')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Logical sequence name, e.g. 'membership_id' or 'application_number'.", max_length=50)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_counters', to='core.association')),
            ],
            options={
                'verbose_name': 'Sequence Counter',
                'verbose_name_plural': 'Sequence Counters',
                'constraints': [models.UniqueConstraint(fields=('association', 'key'), name='unique_sequence_per_association')],
            },
        ),
    ]
