# Generated by Django 6.0.6 on 2026-06-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='donation_details',
            field=models.TextField(blank=True, help_text='Bank name, account name, and account number for donations — free text so it can be formatted however makes sense.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leadership_text',
            field=models.TextField(blank=True, help_text="Free-text leadership/executive listing for the About page. Kept as a single editable block rather than a separate Leadership model for now — easy to upgrade to per-person profiles with photos later if that's ever needed; today this is just a content block, like Mission/Vision."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='motto',
            field=models.CharField(blank=True, help_text='Short tagline shown under the name, e.g. "Unity in Service".', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Shown in the landing page hero, below the motto.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text='Brief history of the association, shown on the About page.'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='core.association')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
