# Generated by Django 6.0.6 on 2026-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='is_active',
            new_name='is_enabled',
        ),
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('election', 'position', 'name'), name='unique_candidate_name_per_position_per_election'),
        ),
    ]
