# Generated by Django 6.0.6 on 2026-06-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes_cast', models.PositiveIntegerField(default=0, help_text='Votes cast for this position within this election.')),
                ('total_eligible_voters', models.PositiveIntegerField(default=0, help_text='Eligible (voting_status=True) members at snapshot time — same across positions in one election.')),
                ('turnout_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_published', models.BooleanField(default=False, help_text='Gates public visibility once the public results page exists.')),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Election Result Snapshot',
                'verbose_name_plural': 'Election Result Snapshots',
                'ordering': ['election', 'position__display_order'],
            },
        ),
        migrations.CreateModel(
            name='MembershipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('total_approved', models.PositiveIntegerField(default=0)),
                ('total_pending', models.PositiveIntegerField(default=0)),
                ('total_rejected', models.PositiveIntegerField(default=0)),
                ('total_alumni', models.PositiveIntegerField(default=0)),
                ('total_undergraduate', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Snapshot',
                'verbose_name_plural': 'Membership Snapshots',
                'ordering': ['-snapshot_date'],
                'permissions': [('view_analytics_dashboard', 'Can view the analytics dashboard')],
            },
        ),
        migrations.CreateModel(
            name='AgeDistributionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('age_bracket', models.CharField(choices=[('under_18', 'Under 18'), ('18_20', '18–20'), ('21_23', '21–23'), ('24_26', '24–26'), ('27_plus', '27+')], max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_distribution_snapshots', to='core.association')),
            ],
            options={
                'verbose_name': 'Age Distribution Snapshot',
                'verbose_name_plural': 'Age Distribution Snapshots',
                'ordering': ['snapshot_date', 'age_bracket'],
            },
        ),
    ]
