# Generated by Django 6.0.6 on 2026-06-26 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='electionresultsnapshot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='elections.election'),
        ),
        migrations.AddField(
            model_name='electionresultsnapshot',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='elections.position'),
        ),
        migrations.AddField(
            model_name='electionresultsnapshot',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electionresultsnapshot',
            name='winner_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='elections.candidate'),
        ),
        migrations.AddField(
            model_name='membershipsnapshot',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_snapshots', to='core.association'),
        ),
        migrations.AddConstraint(
            model_name='agedistributionsnapshot',
            constraint=models.UniqueConstraint(fields=('association', 'snapshot_date', 'age_bracket'), name='unique_age_bracket_snapshot_per_day'),
        ),
        migrations.AddConstraint(
            model_name='electionresultsnapshot',
            constraint=models.UniqueConstraint(fields=('election', 'position'), name='unique_result_snapshot_per_position'),
        ),
        migrations.AddConstraint(
            model_name='membershipsnapshot',
            constraint=models.UniqueConstraint(fields=('association', 'snapshot_date'), name='unique_membership_snapshot_per_day'),
        ),
    ]
