# Generated by Django 6.0.6 on 2026-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agedistributionsnapshot',
            name='age_bracket',
            field=models.CharField(choices=[('below_16', 'Below 16'), ('16_20', '16–20'), ('21_25', '21–25'), ('26_30', '26–30'), ('31_40', '31–40'), ('41_plus', '41+')], max_length=10),
        ),
    ]
